name: First Workflow
on: workflow_dispatch  #When is the workflow triggered
jobs: 
  first-job: #arbitrary job name
    runs-on: ubuntu-latest #define the 
    steps: 
      - name: Print Greeting
        run: echo "Hello WOrld"
      - name: Print Goodbye
        run: echo "Bye"
